apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-api.fullname" . }}-config
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_HOST: {{ include "python-api.postgresqlHost" . | quote }}
  POSTGRES_PORT: {{ include "python-api.postgresqlPort" . | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  API_VERSION: {{ .Values.config.apiVersion | quote }}
  API_PREFIX: {{ .Values.config.apiPrefix | quote }}
