{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "python-api.fullname" . }}-postgres-secret
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "python-api.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: {{ include "python-api.fullname" . }}-postgres-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.postgresPassword }}
{{- end }}
