{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "python-api.fullname" . }}-secretstore
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.secretStore.projectID | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.secretStore.clusterLocation | default "us-central1" }}
          clusterName: {{ .Values.externalSecrets.secretStore.clusterName | default "gke-cluster" }}
          serviceAccountRef:
            name: {{ include "python-api.serviceAccountName" . }}
{{- end }}
