apiVersion: v2
name: python-api
description: A Helm chart for Python FastAPI User Management Application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Zakhar Savchyn
    email: zakhar.savchyn.dev@gmail.com

dependencies:
  - name: postgresql
    version: "18.1.13"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
